dist: trusty
sudo: required
language: cpp

os:
  - linux

compiler:
  - gcc
  # TODO: - clang

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release CI_NAME=TRAVIS
  # TODO: - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
  # build environment setup script
  - source ci/travis/install-env-$TRAVIS_OS_NAME.sh

script:
  # project build script
  - mkdir build && cd build
  - conan install --build=missing ../ci/conanfile.txt
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DJSON_SPIRIT_CHECK=ON
  - cmake --build .

  # run tests with English locale
  - export LANG=en_US.UTF-8
  - export LC_ALL=en_US.UTF-8
  - locale -k LC_NUMERIC
  - bin/json_spirit_unit_tests
  # disabled: - bin/json_spirit_integration_tests

  # run tests with Russian locale
  - export LANG=ru_RU.UTF-8
  - export LC_ALL=ru_RU.UTF-8
  - locale -k LC_NUMERIC
  - bin/json_spirit_unit_tests
  # disabled: - bin/json_spirit_integration_tests
