
function(custom_enable_cxx17 TARGET)
    if (MSVC)
        set_target_properties(${TARGET} PROPERTIES COMPILE_FLAGS "/std:c++latest")
    endif()
    target_compile_features(${TARGET} PUBLIC cxx_std_17)
endfunction()

function(custom_enable_cxx14 TARGET)
    target_compile_features(${TARGET} PUBLIC cxx_std_14)
endfunction()

function(custom_enable_cxx11 TARGET)
    target_compile_features(${TARGET} PUBLIC cxx_std_11)
endfunction()

function(custom_enable_warnings TARGET)
    if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL GNU)
        target_compile_options(${TARGET} PRIVATE "-Wall" "-Wextra" "-Wpedantic")
    endif()
    if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL Clang)
        target_compile_options(${TARGET} PRIVATE "-Wall" "-Wextra" "-Wpedantic" "-Wdocumentation")
    endif()
endfunction()

function(custom_clang_tidy_checks)
    set(CLANG_TIDY_OPTIONS "clang-tidy;-checks=")
    set(SEPARATOR "")
    foreach(CHECK ${ARGN})
        set(CLANG_TIDY_OPTIONS "${CLANG_TIDY_OPTIONS}${SEPARATOR}${CHECK}")
        set(SEPARATOR ",")
    endforeach()
    set(CMAKE_CXX_CLANG_TIDY ${CLANG_TIDY_OPTIONS} PARENT_SCOPE)
endfunction(custom_clang_tidy_checks)
